### ISSUE TITLE
Configuring OpenAM

### ISSUE THREAD

**Issue by andymc** [mak-it/omniauth-openam#1]
Is there a pointer to documentation about what we need to do on the OpenAM side to make this work? Does this act as the agent for SSO in One Domain like here: https://backstage.forgerock.com/#!/docs/openam/12.0.0/admin-guide/chap-sso ? 
Would it work for cross-domain as well?

**Comment by ebeigarts** [comment]
@andymc it works only on the same domain `*.example.net`. Maybe you can use [OAuth with OpenAM](https://backstage.forgerock.com/#!/docs/openam/12.0.0/admin-guide#chap-mobile)?

**Comment by andymc** [comment]
Thanks Edgars!
