### ISSUE TITLE
Custom session attributes from SSOToken in User Hash

### ISSUE THREAD

**Issue by ismail44** [mak-it/omniauth-openam#2]
Is there a way to request custom session attributes being set by a Post Authentication Processor? For example, we have written a Post Authentication Processor that runs after a successful authentication. It adds several properties to the SSOToken. These values are available when doing an /identity/attributes search, however, you need to ask for them by name (they don't come back by default).

**Comment by ebeigarts** [comment]
I guess not. How do you ask for them by name? Is there a documentation for this? Anyway, pull requests are welcome.

**Comment by ismail44** [comment]
To ask for them you just pass in a query string parameter of `attributenames` for every parameter you want returned. Pass it in multiple times for every named parameter. Note, this will ONLY give you back what you ask for. 

I didn't find it very well documented from ForgeRock, however, I found it deep into one of their message boards. It works, because I am using it now to grab those values, however, I am looking to switch from our home-grown authentication module to OmniAuth and came across your strategy. 

Thanks for the reply.

**Comment by ebeigarts** [comment]
I think we could add additional option for the strategy to support this `option :attribute_names, []`. Can you create a pull request for this?
